### ISSUE TITLE
Make TraceSink public

### ISSUE THREAD

**Issue by makhdumi** [serilog/serilog-sinks-trace#4]
I need to log JSON-formatted data to Trace, or at least the Console. 

TraceSink and the others are all internal, so I cannot specify a custom formatter.  Nor can I specify a formatter from the extension method.

If these sinks are private for a reason, is there any way of using a custom formatter, other than creating a custom sink?

**Comment by nblumhardt** [comment]
Hi there, sorry about the lacking response on this. In the great 1.5 -> 2.0 repository shuffle I missed "watching" this repository.

I have added the missing overload and a 2.1 build with it will be out soon. There's no pressing reason not to make the sink class public, except that in other cases we've found it useful to be able to split sink implementations into multiple different options and switch between them based on the configuration. Making the types public would interfere with this, if we decide to do it here in the future, so adding the missing methods to the configuration API is preferable.

Thanks for raising the issue!
