### ISSUE TITLE
Change all to WriteLine

### ISSUE THREAD

**Issue by dasjestyr** [serilog/serilog-sinks-trace#7]
Just a recommendation:

Visual studio messes with the formatting when you use Trace.TraceWarning, Trace.TraceInformation, Trace.TraceError which is really annoying. I recommend making them all Trace.WriteLine since the args aren't being used anyway. This ensures they're all printed the same way.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, Jeremy. Definitely open to a change here, if anyone's able to PR and provide a quick example of the before/after output 👍

**Comment by dasjestyr** [comment]
PR - https://github.com/serilog/serilog-sinks-trace/pull/8

**Comment by spelltwister** [comment]
Can you explain more why you would do this?  For example, if I have trace listeners setup (for app insights for example), then I would very much want to know that it was an error, warning, info, etc... By just outputting a trace via writeline, I lose this classification.

Normally, using Trace.WriteLine, you'd check the trace level first, then output.  Eg, 

    if(isError && switch.TraceError) { Trace.WriteLine("Error message"); }

With this update, switches in web.config cannot change the behavior of logging.

Seems like this change is only thinking about the debug window which is probably the least important output to support.

**Comment by nblumhardt** [comment]
@spelltwister thanks for the query. Your points seem valid - @dasjestyr what do you think? Did we miss the mark with #8? Wondering if we'd be better off publishing a _Serilog.Sinks.Debug_ package to handle debug window output..

**Comment by dasjestyr** [comment]
Yeah I suppose that makes sense. A debug sink would probably be more appropriate. I think I tend to default to trace because of the old PCL libs not having the diagnostics namespace.

**Comment by nblumhardt** [comment]
Thanks @dasjestyr.

Just published: https://github.com/serilog/serilog-sinks-debug

Will need to back out the recent target change; hopefully we can preserve some of the other improvements in the PR. Cheers!

**Comment by spelltwister** [comment]
Thanks for reconsidering this change!  :)

**Comment by EamonHetherton** [comment]
Just ran into this issue because I was expecting my errors to come out of the trace as error and when investigating it turns out that this pull request was merged but never "un-merged" when the decision was made that the changes belong in another sink instead.  Any chance of reverting PR #8 and getting a new build?

**Comment by EamonHetherton** [comment]
PR #9 reverts the code changes from PR #8 but keeps the projects and build updates

**Comment by mikaelmello** [comment]
I believe this issue can be closed
